"""empty message

Revision ID: a747dabf17ed
Revises: 
Create Date: 2021-04-12 22:31:48.781229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a747dabf17ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('searched_scripts', 'stockscriptoutput',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('searched_scripts', 'stockscriptoutput',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
